runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /https://royceswebsite.appspot.com/
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)